name: dev_libraries
description: A set of common patterns to be used across all Flutter projects
publish_to: 'none'
version: 2.0.1
homepage: https://www.google.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #frameworks
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1

  #services
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  google_sign_in: ^5.0.4
  google_maps_webservice: ^0.0.20-nullsafety.5
  #flutter_stripe: ^2.1.1
  #stripe_payment: ^1.1.1
  #admob_flutter: ^2.0.0-nullsafety.1
  
  in_app_purchase: ^1.0.4
  #appspector: '0.4.0'
  #usage: ^3.4.1 //google analytics

  #libraries
  equatable: ^2.0.3
  sqflite: 2.0.0+3
  rxdart: ^0.27.1
  flat: ^0.4.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  bloc_test: ^8.0.0
  mockito: ^5.0.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
